# Generated by Django 4.2.3 on 2023-07-04 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('q_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Question',
                'ordering': ['q_uid'],
                'get_latest_by': ['q_uid'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('t_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('t_questions', models.ManyToManyField(to='API.question')),
            ],
            options={
                'verbose_name': 'Test',
                'ordering': ['t_uid'],
                'get_latest_by': ['t_uid'],
            },
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('tt_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tt_name', models.CharField(max_length=20)),
                ('tt_text', models.TextField()),
            ],
            options={
                'verbose_name': 'ExamType',
                'ordering': ['tt_uid'],
                'get_latest_by': ['tt_uid'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('tr_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tr_date_start', models.DateTimeField(auto_now_add=True)),
                ('tr_date_end', models.DateTimeField(null=True)),
                ('tr_score', models.IntegerField()),
                ('tr_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.test')),
                ('tr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TestResult',
                'ordering': ['tr_uid'],
                'get_latest_by': ['tr_uid'],
            },
        ),
        migrations.AddField(
            model_name='test',
            name='t_testType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.testtype'),
        ),
        migrations.AddField(
            model_name='question',
            name='q_testType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.testtype'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('a_uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('a_text', models.TextField()),
                ('a_correct', models.BooleanField()),
                ('a_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='API.question')),
            ],
            options={
                'verbose_name': 'Answer',
                'ordering': ['a_uid'],
                'get_latest_by': ['a_uid'],
            },
        ),
    ]
