# Generated by Django 4.2.3 on 2023-07-11 13:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='a_created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='question',
            name='q_created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='question',
            name='q_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='test',
            name='t_created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='testtype',
            name='tt_created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a_correct',
            field=models.BooleanField(verbose_name='Is correct?'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='API.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a_text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='a_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_testType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.testtype', verbose_name='Test type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='test',
            name='t_questions',
            field=models.ManyToManyField(to='API.question', verbose_name='Questions'),
        ),
        migrations.AlterField(
            model_name='test',
            name='t_testType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.testtype', verbose_name='Test type'),
        ),
        migrations.AlterField(
            model_name='test',
            name='t_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='tr_date_end',
            field=models.DateTimeField(null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='tr_date_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='tr_score',
            field=models.IntegerField(verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='tr_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='tr_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='tr_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='tt_name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='tt_text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='tt_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UID'),
        ),
    ]
