# Generated by Django 4.2.3 on 2023-07-11 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_answer_a_created_at_question_q_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='a_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='test',
            name='t_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='tr_date_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='tt_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
