# Generated by Django 4.2.3 on 2023-07-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_answer_a_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_id',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
