# Generated by Django 4.2.3 on 2023-07-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_question_q_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_id',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
