# Generated by Django 4.2.3 on 2023-07-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_question_q_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtype',
            name='tt_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Name'),
        ),
    ]
